version: '3.3'

services:
  postgresql:
    image: postgresql
    networks:
      - api-node
    ports:
      - 10002:5432
    environment:
      - POSTGRES_USER=apinode
      - POSTGRE_PASSWORD=apinodepass
  mongodb:
    image: mongodb
    networks:
      - api-node
    ports:
      - 10001:27017
  app:
    depends_on:
      - postgresql
      - mongodb
    networks:
      - api-node
    ports:
      - 10000:80

networks:
  api-node:
    external: true