version: '3.9'

services:
  postgresql:
    image: postgres:latest
    restart: always
    networks:
      - api-node
    ports:
      - 10002:5432
    environment:
      - POSTGRES_USER=apinode
      - POSTGRES_PASSWORD=apinodepass
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=apinode
      - MONGO_INITDB_ROOT_PASSWORD=apinodepass
    networks:
      - api-node
    ports:
      - 10001:27017

networks:
  api-node:
    external: true